baseURL: 'https://husky-dev.me/'
languageCode: "en"
title: "Husky Dev"
theme: "PaperMod"
timeout: "5m"

menu:
  main:
    - identifier: github
      name: "GitHub"
      url: "https://github.com/husky-dev"
      weight: 1
    - identifier: projects
      name: "ğŸ› ï¸ Projects"
      url: "/projects"
      weight: 2
    - identifier: cv
      name: "ğŸ‘¨â€ğŸ’¼ CV"
      url: "/cv"
      weight: 3
    - identifier: blog
      name: "ğŸ‘¨â€ğŸ’» Blog"
      url: "https://blog.husky-dev.me/en"
      weight: 4
    - identifier: ukraine
      name: "ğŸ‡ºğŸ‡¦ Support Ukraine"
      url: "https://prytulafoundation.org/en/donation"
      weight: 5

params:
  defaultTheme: auto
  displayFullLangName: true
  profileMode:
    enabled: true
    homeInfoParams:
    title: "Hello!"
    subtitle: "My name is Jaroslav, and I have over 14 years of experience as a programmer. I love to code for both work and leisure. On this site, you'll find more information about me and the projects."
    imageUrl: "avatar-003.jpg"
    buttons:
      - name: "GitHub"
        url: "https://github.com/husky-dev"
        weight: 1
      - name: "ğŸ› ï¸ Projects"
        url: "/projects"
        weight: 2
      - name: "ğŸ‘¨â€ğŸ’¼ CV"
        url: "/cv"
        weight: 3
      - name: "ğŸ‘¨â€ğŸ’» Blog"
        url: "https://blog.husky-dev.me/en"
        weight: 4
      - name: "ğŸ‡ºğŸ‡¦ Support Ukraine"
        url: "https://prytulafoundation.org/en/donation"
        weight: 5

  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/husky.dev/"
    - name: "facebook"
      url: "https://fb.me/huskydev"
    - name: "twitter"
      url: "https://twitter.com/HuskyDevUA"
    - name: "github"
      url: "https://github.com/husky-dev"
    - name: "email"
      url: "mailto:hello@husky-dev.me"

defaultContentLanguage: "en"

languages:
  en:
    weight: 1
    languageName: "En"
  uk:
    weight: 2
    languageName: "ğŸ‡ºğŸ‡¦ Uk"
    params:
      profileMode:
        enabled: true
        homeInfoParams:
        title: "ĞŸÑ€Ğ¸Ğ²Ñ–Ñ‚!"
        subtitle: "ĞœĞµĞ½Ğµ Ğ·Ğ²ÑƒÑ‚ÑŒ Ğ¯Ñ€Ğ¾ÑĞ»Ğ°Ğ², Ñ– Ñ Ğ¼Ğ°Ñ Ğ¿Ğ¾Ğ½Ğ°Ğ´ 14 Ñ€Ğ¾ĞºÑ–Ğ² Ğ´Ğ¾ÑĞ²Ñ–Ğ´Ñƒ Ñ€Ğ¾Ğ±Ğ¾Ñ‚Ğ¸ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ñ–ÑÑ‚Ğ¾Ğ¼. Ğ¯ Ğ»ÑĞ±Ğ»Ñ Ğ¿Ğ¸ÑĞ°Ñ‚Ğ¸ ĞºĞ¾Ğ´ ÑĞº Ğ´Ğ»Ñ Ñ€Ğ¾Ğ±Ğ¾Ñ‚Ğ¸, Ñ‚Ğ°Ğº Ñ– Ğ´Ğ»Ñ Ğ²Ñ–Ğ´Ğ¿Ğ¾Ñ‡Ğ¸Ğ½ĞºÑƒ. ĞĞ° Ñ†ÑŒĞ¾Ğ¼Ñƒ ÑĞ°Ğ¹Ñ‚Ñ– Ğ²Ğ¸ Ğ·Ğ½Ğ°Ğ¹Ğ´ĞµÑ‚Ğµ Ñ–Ğ½Ñ„Ğ¾Ñ€Ğ¼Ğ°Ñ†Ñ–Ñ Ğ¿Ñ€Ğ¾ Ğ¼ĞµĞ½Ğµ Ñ‚Ğ° Ğ¼Ğ¾Ñ— Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ğ¸."
        imageUrl: "avatar-003.jpg"
        buttons:
          - name: "GitHub"
            url: "https://github.com/husky-dev"
            weight: 1
          - name: "ğŸ› ï¸ ĞŸÑ€Ğ¾ĞµĞºÑ‚Ğ¸"
            url: "/uk/projects"
            weight: 2
          - name: "ğŸ‘¨â€ğŸ’¼ Ğ ĞµĞ·ÑĞ¼Ğµ"
            url: "/uk/cv"
            weight: 3
          - name: "ğŸ‘¨â€ğŸ’» Ğ‘Ğ»Ğ¾Ğ³"
            url: "https://blog.husky-dev.me/"
            weight: 4
          - name: "ğŸ‡ºğŸ‡¦ Ğ”Ğ¾Ğ¿Ğ¾Ğ¼Ğ¾Ğ³Ñ‚Ğ¸ Ğ£ĞºÑ€Ğ°Ñ—Ğ½Ñ–"
            url: "https://prytulafoundation.org/donation"
            weight: 5
    menu:
      main:
        - identifier: github
          name: "GitHub"
          url: "https://github.com/husky-dev"
          weight: 1
        - identifier: projects
          name: "ğŸ› ï¸ ĞŸÑ€Ğ¾ĞµĞºÑ‚Ğ¸"
          url: "/uk/projects"
          weight: 2
        - identifier: cv
          name: "ğŸ‘¨â€ğŸ’¼ Ğ ĞµĞ·ÑĞ¼Ğµ"
          url: "/uk/cv"
          weight: 3
        - identifier: blog
          name: "ğŸ‘¨â€ğŸ’» Ğ‘Ğ»Ğ¾Ğ³"
          url: "https://blog.husky-dev.me/"
          weight: 4
        - identifier: ukraine
          name: "ğŸ‡ºğŸ‡¦ Ğ”Ğ¾Ğ¿Ğ¾Ğ¼Ğ¾Ğ³Ñ‚Ğ¸ Ğ£ĞºÑ€Ğ°Ñ—Ğ½Ñ–"
          url: "https://prytulafoundation.org/donation"
          weight: 5
