baseURL: 'https://husky-dev.me/'
languageCode: "uk"
title: "ğŸ‘¨â€ğŸ’» Husky Dev"
theme: "PaperMod"
timeout: "5m"

menu:
  main:
    - identifier: blog
      name: "ğŸ‘¨â€ğŸ’» Ğ‘Ğ»Ğ¾Ğ³"
      url: "https://blog.husky-dev.me/"
      weight: 1
    - identifier: ukraine
      name: "ğŸ‡ºğŸ‡¦ Ğ”Ğ¾Ğ¿Ğ¾Ğ¼Ğ¾Ğ³Ñ‚Ğ¸ Ğ£ĞºÑ€Ğ°Ñ—Ğ½Ñ–"
      url: "https://prytulafoundation.org/en/donation"
      weight: 2

params:
  defaultTheme: auto
  displayFullLangName: true
  profileMode:
    enabled: true
    homeInfoParams:
    title: "ĞŸÑ€Ğ¸Ğ²Ñ–Ñ‚!"
    subtitle: "ĞœĞµĞ½Ğµ Ğ·Ğ²Ğ°Ñ‚Ğ¸ Ğ¯Ñ€Ğ¾ÑĞ»Ğ°Ğ². Ğ¯ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ñ–ÑÑ‚, Ğ»ÑĞ±Ğ»Ñ ÑĞ¿Ğ¾Ñ€Ñ‚ Ñ– Ğ¿Ğ¾Ğ´Ğ¾Ñ€Ğ¾Ğ¶Ñ–."
    imageUrl: "avatar-001.jpg"
    buttons:
      - name: "ğŸ‘¨â€ğŸ’» Ğ‘Ğ»Ğ¾Ğ³"
        url: "https://blog.husky-dev.me/"
        weight: 1
      - name: "ğŸ‡ºğŸ‡¦ Ğ”Ğ¾Ğ¿Ğ¾Ğ¼Ğ¾Ğ³Ñ‚Ğ¸ Ğ£ĞºÑ€Ğ°Ñ—Ğ½Ñ–"
        url: "https://prytulafoundation.org/en/donation"
        weight: 2

  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/husky.dev/"
    - name: "facebook"
      url: "https://www.facebook.com/snipter"
    - name: "twitter"
      url: "https://twitter.com/HuskyDevUA"
    - name: "github"
      url: "https://github.com/husky-dev"
    - name: "email"
      url: "mailto:hello@husky-dev.me"

defaultContentLanguage: "uk"

languages:
  uk:
    weight: 1
    languageName: "ğŸ‡ºğŸ‡¦"
  en:
    weight: 2
    languageName: "ğŸ‡ºğŸ‡¸"
    params:
      profileMode:
        enabled: true
        homeInfoParams:
        title: "Hello!"
        subtitle: "My name is Jaroslav. I am a programmer. I love sports and traveling."
        imageUrl: "avatar-001.jpg"
        buttons:
          - name: "ğŸ‘¨â€ğŸ’» Blog"
            url: "https://blog.husky-dev.me/"
            weight: 1
          - name: "ğŸ‡ºğŸ‡¦ Support Ukraine"
            url: "https://prytulafoundation.org/en/donation"
            weight: 2
    menu:
      main:
        - identifier: blog
          name: "ğŸ‘¨â€ğŸ’» Blog"
          url: "https://blog.husky-dev.me/"
          weight: 1
        - identifier: ukraine
          name: "ğŸ‡ºğŸ‡¦ Support Ukraine"
          url: "https://prytulafoundation.org/en/donation"
          weight: 2
