baseURL: 'https://husky-dev.me/'
languageCode: "en"
title: "ğŸ‘¨â€ğŸ’» Husky Dev"
theme: "PaperMod"
timeout: "5m"

menu:
  main:
    - identifier: github
      name: "GitHub"
      url: "https://github.com/husky-dev"
      weight: 1
    - identifier: open-source
      name: "Open Source"
      url: "/open-source"
      weight: 2
    - identifier: blog
      name: "ğŸ‘¨â€ğŸ’» Blog"
      url: "https://blog.husky-dev.me/"
      weight: 2
    - identifier: ukraine
      name: "ğŸ‡ºğŸ‡¦ Support Ukraine"
      url: "https://prytulafoundation.org/en/donation"
      weight: 3

params:
  defaultTheme: auto
  displayFullLangName: true
  profileMode:
    enabled: true
    homeInfoParams:
    title: "Hello!"
    subtitle: "My name is Jaroslav. I am a programmer. I love programming, traveling and sports."
    imageUrl: "avatar-003.jpg"
    buttons:
      - name: "GitHub"
        url: "https://github.com/husky-dev"
        weight: 1
      - name: "Open Source"
        url: "/open-source"
        weight: 2
      - name: "ğŸ‘¨â€ğŸ’» Blog"
        url: "https://blog.husky-dev.me/en/"
        weight: 3
      - name: "ğŸ‡ºğŸ‡¦ Support Ukraine"
        url: "https://prytulafoundation.org/en/donation"
        weight: 4

  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/husky.dev/"
    - name: "facebook"
      url: "https://fb.me/huskydev"
    - name: "twitter"
      url: "https://twitter.com/HuskyDevUA"
    - name: "github"
      url: "https://github.com/husky-dev"
    - name: "email"
      url: "mailto:hello@husky-dev.me"

defaultContentLanguage: "en"

languages:
  en:
    weight: 1
    languageName: "En"
  uk:
    weight: 2
    languageName: "ğŸ‡ºğŸ‡¦ Uk"
    params:
      profileMode:
        enabled: true
        homeInfoParams:
        title: "ĞŸÑ€Ğ¸Ğ²Ñ–Ñ‚!"
        subtitle: "ĞœĞµĞ½Ğµ Ğ·Ğ²Ğ°Ñ‚Ğ¸ Ğ¯Ñ€Ğ¾ÑĞ»Ğ°Ğ². Ğ¯ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ñ–ÑÑ‚. Ğ›ÑĞ±Ğ»Ñ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼ÑƒĞ²Ğ°Ğ½Ğ½Ñ, Ğ¿Ğ¾Ğ´Ğ¾Ñ€Ğ¾Ğ¶Ñ– Ñ– ÑĞ¿Ğ¾Ñ€Ñ‚."
        imageUrl: "avatar-003.jpg"
        buttons:
          - name: "GitHub"
            url: "https://github.com/husky-dev"
            weight: 1
          - name: "Open Source"
            url: "/open-source"
            weight: 2
          - name: "ğŸ‘¨â€ğŸ’» Ğ‘Ğ»Ğ¾Ğ³"
            url: "https://blog.husky-dev.me/"
            weight: 3
          - name: "ğŸ‡ºğŸ‡¦ Ğ”Ğ¾Ğ¿Ğ¾Ğ¼Ğ¾Ğ³Ñ‚Ğ¸ Ğ£ĞºÑ€Ğ°Ñ—Ğ½Ñ–"
            url: "https://prytulafoundation.org/donation"
            weight: 4
    menu:
      main:
        - identifier: github
          name: "GitHub"
          url: "https://github.com/husky-dev"
          weight: 1
        - identifier: open-source
          name: "Open Source"
          url: "/open-source"
          weight: 2
        - identifier: blog
          name: "ğŸ‘¨â€ğŸ’» Ğ‘Ğ»Ğ¾Ğ³"
          url: "https://blog.husky-dev.me/"
          weight: 3
        - identifier: ukraine
          name: "ğŸ‡ºğŸ‡¦ Ğ”Ğ¾Ğ¿Ğ¾Ğ¼Ğ¾Ğ³Ñ‚Ğ¸ Ğ£ĞºÑ€Ğ°Ñ—Ğ½Ñ–"
          url: "https://prytulafoundation.org/donation"
          weight: 4
